!function(){let a=document.querySelector(".app"),i=io(),t,u=null,l=null;function n(){var e=a.querySelector(".chat-screen #message-input").value;0!=e.length&&(u?(i.emit("edit-message",{messageId:u,newText:e}),u=null):(r("my",e={id:Date.now(),username:t,text:e,replyTo:l}),i.emit("chat",e)),a.querySelector(".chat-screen #message-input").value="",l=null)}function r(e,t){var n,r,s=a.querySelector(".chat-screen .messages");let c=document.createElement("div"),o=(c.setAttribute("class",`message ${e}-message`),c.setAttribute("data-id",t.id),"");t.replyTo&&(n=document.querySelector(`.message[data-id="${t.replyTo}"] .text`),r=document.querySelector(`.message[data-id="${t.replyTo}"] .name`).textContent,n)&&(o=`<div class="reply-to-text">${r}: ${n.textContent}</div>`),"my"===e?c.innerHTML=`
        <div>
          <div class="name" id="moi">Vous</div>
          ${o}
          <div class="text">${t.text.replace(/\n/g,"<br>")}</div>
          <button class="edit-btn">Modifier</button>
          <button class="delete-btn">Supprimer</button>
          <button class="reply-btn">Répondre</button>
        </div>`:"other"===e?c.innerHTML=`
        <div>
          <div class="name" id="lui">${t.username}</div><br>
          ${o}
          <div class="text">${t.text.replace(/\n/g,"<br>")}</div>
          <button class="reply-btn">Répondre</button>
        </div>`:"update"===e&&(c.setAttribute("class","update"),c.innerHTML=t),s.appendChild(c),"my"!==e&&"other"!==e||(c.addEventListener("contextmenu",function(e){e.preventDefault();var e=c.querySelector(".edit-btn"),t=c.querySelector(".delete-btn"),n=c.querySelector(".reply-btn");e&&e.classList.add("show"),t&&t.classList.add("show"),n.classList.add("show")}),"my"===e&&(c.querySelector(".edit-btn").addEventListener("click",function(){var e=c.querySelector(".text").textContent;a.querySelector(".chat-screen #message-input").value=e,u=t.id}),c.querySelector(".delete-btn").addEventListener("click",function(){confirm("Êtes-vous sûr de vouloir supprimer ce message ?")&&i.emit("delete-message",t.id)})),c.querySelector(".reply-btn").addEventListener("click",function(){l=t.id,a.querySelector(".chat-screen #message-input").value="",a.querySelector(".chat-screen #message-input").focus()})),document.addEventListener("click",function(e){var t,n;c.contains(e.target)||(e=c.querySelector(".edit-btn"),t=c.querySelector(".delete-btn"),n=c.querySelector(".reply-btn"),e&&e.classList.remove("show"),t&&t.classList.remove("show"),n.classList.remove("show"))}),s.scrollTop=s.scrollHeight-s.clientHeight}a.querySelector(".join-screen #join-user").addEventListener("click",function(){var e=a.querySelector(".join-screen #username").value,t=a.querySelector(".join-screen #password_student").value;0!=e.length&&0!=t.length&&i.emit("newuser",{username:e,password_student:t})}),i.on("username-taken",function(e){alert(e)}),i.on("auth-error",function(e){alert(e)}),i.on("auth-success",function(){a.querySelector(".join-screen").classList.remove("active"),a.querySelector(".chat-screen").classList.add("active"),t=a.querySelector(".join-screen #username").value}),i.on("load-messages",function(e){e.forEach(e=>{r(e.username===t?"my":"other",e)})}),i.on("update",function(e){r("update",e)}),a.querySelector(".chat-screen #send-message").addEventListener("click",function(){n()}),a.querySelector(".chat-screen #message-input").addEventListener("keydown",function(e){"Enter"!==e.key||e.shiftKey||(e.preventDefault(),n())}),a.querySelector(".chat-screen #exit-chat").addEventListener("click",function(){i.emit("exituser",t),window.location.href=window.location.href}),i.on("chat",function(e){r("other",e)}),i.on("delete-message",function(e){(e=document.querySelector(`.message[data-id="${e}"]`))&&e.remove()}),i.on("edit-message",function({messageId:e,newText:t}){(e=document.querySelector(`.message[data-id="${e}"] .text`))&&(e.textContent=t)})}();